ID=asahiart.fontsubset
VERSION=1.0.0
GROUP=asahiart.fontsubset
DISPLAY_NAME=AsahiArt Font Subset
DESCRIPTION=Subset TTF and OTF font files in Gradle builds using explicit Unicode character lists
WEBSITE=https://github.com/AsahiArt/font-subset-gradle-plugin
VCS_URL=https://github.com/AsahiArt/font-subset-gradle-plugin
IMPLEMENTATION_CLASS=asahiart.fontsubset.FontSubsetPlugin
